### PR TITLE
Mark container component to copy to client

### PR DESCRIPTION
**Pull request by eclipseisoffline**
This PR marks the `minecraft:container` item component as copy to client, and includes a component transformer mixin for converting the Polymer items in the component to their client side form.

This is mainly useful for shulker box preview mods. Whereas before, any shulker box preview would break with shulker boxes containing Polymer items (instead just showing an empty shulker box), now, the preview correctly shows all items including the Polymer ones.

### CODE REVIEW

**Comment by Patbox** [comment]
Hmm, converion of container shouldn't be needed, due it using itemstack network codec already altered by polymer

**Comment by eclipseisoffline** [comment]
Hm, unable to test right now, but I can test tomorrow without the converter
If it works fine, I'll make sure to remove it from the PR

**Comment by eclipseisoffline** [comment]
Does indeed seem to work fine without the mixin, though the Polymer server-side items still show up unconverted in `/polymer client-item`

**Comment by Patbox** [comment]
Copied the change manually (and included it on 1.20.6 branch)

**Pull request closed without merging**
